name: 'Mirror Repo'
on:
  push:
    branches: [__mirror]
  schedule:
    - cron: '*/5 * * * *'   # Run 
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://github.com/rkeyoceannetworks/cloudloop-mqtt'
          exclude: '.github/workflows/**'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
